spring:
  application:
    name: customer
  profiles:
    active: production
  datasource:
    url: jdbc:mysql://localhost:3306/kodilla_customer?serverTimezone=Europe/Warsaw&useSSL=False
    username: ${customer.datasource.username}
    password: ${customer.datasource.password}
# ACTUATOR INFO
info:
  app:
    name: "Customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client: ${eureka-client}